"use strict";
let x = 5;
let y = 10;
let name1 = "Ayan";
let isAdmin = true;
let fruits = ["apple", "banana", "orange"];
let emptyArray = [];
let country = "Canada";
let age = 25;
let language = "JavaScript";
console.log("Is x greater than y? I predict False.");
console.log(x > y);
console.log("Is name equal to 'Ayan'? I predict True.");
console.log(name1 === 'Ayan');
console.log("Is isAdmin equal to true? I predict True.");
console.log(isAdmin === true);
console.log("Is 'banana' in the fruits array? I predict True.");
console.log(fruits.includes('banana'));
console.log("Is emptyArray empty? I predict True.");
console.log(emptyArray.length === 0);
console.log("Is country not equal to 'USA'? I predict True.");
console.log(country !== 'USA');
console.log("Is age less than or equal to 18? I predict False.");
console.log(age <= 18);
console.log("Is age greater than 21? I predict True.");
console.log(age > 21);
console.log("Is language equal to 'Python'? I predict False.");
console.log(language === 'Python');
console.log("Is x plus y equal to 15? I predict True.");
console.log(x + y === 15);
